[package]
name = "h2s"
version = "0.1.0"
authors = ["Naoto Ikeno <ikenox@gmail.com>"]
edition = "2021"
repository = "https://github.com/ikenox/h2s-rs"
description = """
A declarative HTML parser library.
"""
license = "MIT"
readme = "README.md"

[workspace]
members = ["macro", "core"]

[dependencies]
h2s_core = { version = "=0.1.0", path = "core" }
h2s_macro = { version = "=0.1.0", path = "macro" }

[dev-dependencies]
scraper = "0.13.0"
skeptic = "0.13"

[build-dependencies]
skeptic = "0.13"