[package]
name = "h2s"
description = "A declarative HTML parser library."
version = "0.1.0"
authors = ["Naoto Ikeno <ikenox@gmail.com>"]
repository = "https://github.com/ikenox/h2s-rs"
license = "MIT"
readme = "README.md"
edition = "2021"
rust-version = "1.65"

categories = ["parsing"]
keywords = ["html", "dom", "parser"]

[workspace]
members = ["macro", "core"]

[dependencies]
h2s_core = { version = "=0.1.0", path = "core" }
h2s_macro = { version = "=0.1.0", path = "macro" }

[dev-dependencies]
scraper = "0.13.0"
skeptic = "0.13"

[build-dependencies]
skeptic = "0.13"