[package]
name = "h2s"
description = "A declarative HTML parser"
version = "0.1.2"
authors = ["Naoto Ikeno <ikenox@gmail.com>"]
repository = "https://github.com/ikenox/h2s-rs"
license = "MIT"
readme = "README.md"
edition = "2021"
rust-version = "1.65"

categories = ["parsing"]
keywords = ["html", "dom", "parser"]

[workspace]
members = ["macro", "core"]

[dependencies]
h2s_core = { version = "=0.1.1", path = "core" }
h2s_macro = { version = "=0.1.1", path = "macro" }

itertools = "0.10.3"
scraper = { version = "0.13.0", optional = true }

[features]
default = ["backend-scraper"]
backend-scraper = ["dep:scraper"]

