[package]
name = "h2s_macro"
version = "0.1.0"
authors = ["Naoto Ikeno <ikenox@gmail.com>"]
edition = "2021"
repository = "https://github.com/ikenox/h2s"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.18"
syn = "1.0.92"
darling = "0.14.1"
proc-macro2 = "1.0.38"
kuchiki = "0.8.1"
h2s_core = { version = "=0.1.0", path = "../core" }

[lib]
proc-macro = true