[package]
name = "h2s_core"
description = "A core part of h2s"
version = "0.18.0"
authors = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
