[package]
name = "h2s_core"
version = "0.1.0"
authors = ["Naoto Ikeno <ikenox@gmail.com>"]
edition = "2021"
repository = "https://github.com/ikenox/h2s"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
scraper = { version = "0.13.0", optional = true }

[dev-dependencies]
maplit = "1.0.2"

[features]
default = ["backend-scraper"]
backend-scraper = ["dep:scraper"]