name: Cargo publish
on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  cargo-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install cargo-release
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-release
      - run: cargo release publish --workspace --execute --no-confirm
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
