name: Cargo publish
on:
  release:
    types:
      - published

jobs:
  cargo-publish:
    steps:
      - uses: actions/checkout@v3
      - name: install cargo-release
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-release
      - run: cargo release publish --workspace --execute --no-confirm
