name: Cargo publish
on:
  release:
    types:
      - published

jobs:
  cargo-publish:
    steps:
      - uses: actions/checkout@v3
      - name: Install cargo-release
        uses: taiki-e/install-action@v1
        with:
          tool: cargo-release
      - run: cargo release publish --workspace --execute --no-confirm
