name: CI

on:
  push:
  schedule: [ cron: "7 0 * * *" ]

env:
  RUST_BACKTRACE: 1

jobs:
  readme:
    name: check README.md is up-to-date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install cargo-rdme
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-rdme
      - uses: Swatinem/rust-cache@v1
      - run: cargo rdme --check
  rustfmt:
    name: check the code is correctly formatted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - name: format all files
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  test:
    name: test on ${{ matrix.os }} with ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { rust: nightly, os: ubuntu-latest }
          - { rust: 1.65, os: ubuntu-latest }
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: cargo version
        run: cargo --version
      - run: cargo test --workspace --all-targets
      - run: cargo test --workspace --doc
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - name: run clippy
        run: cargo clippy --workspace --all-targets
