name: Create release pull request
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true
        type: string
jobs:
  release:
    permissions:
      id-token: write # Enable OIDC
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: chainguard-dev/actions/setup-gitsign@main
      - name: install cargo-release
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-release
      - run: echo "BRANCH_NAME="h2s-v${{ inputs.version }}" >> $GITHUB_ENV
      - run: git checkout -b $BRANCH_NAME
      - run: cargo release version ${{ inputs.version }} --workspace --execute --no-confirm
      - run: git commit -am "v${{ inputs.version }}"
      - run: git push origin $BRANCH_NAME
      - run: gh pr create --base main --head $BRANCH_NAME --title "v${{ inputs.version }}" --fill
        env:
          GH_TOKEN: ${{ github.token }}
      - run: gh pr merge $BRANCH_NAME -d --merge --auto
        env:
          GH_TOKEN: ${{ github.token }}
