name: Release
on:
  push:
    branches: [ release ]

jobs:
  cargo-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install cargo-release
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-release
      - run: echo "RELEASE_VERSION=$(cargo metadata --no-deps --format-version=1 | jq -r '.packages[] | select(.name == "h2s") | .version')" >> $GITHUB_ENV
      - run: gh release create "v$RELEASE_VERSION" -t "v$RELEASE_VERSION" --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
      - run: cargo release publish --workspace --execute --no-confirm
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
